Repository hetznercloud/hcloud-go, pull requests merged in 2023-12, with the labels that each got.

#349 feat: add missing properties
  hcloud/datacenter.go
  hcloud/load_balancer_type.go
  hcloud/schema/datacenter.go
  hcloud/schema/load_balancer_type.go
  hcloud/schema/server.go
  hcloud/schema_gen.go
  hcloud/server.go
  hcloud/zz_schema.go
Labels: Feature

#354 fix: schema conversion outputs debug messages to stdout
  hcloud/schema_gen.go
Labels: Bug

#359 ci: update release-please-action to v4
  .github/release-please-config.json
  .github/release-please-manifest.json
  .github/workflows/release-please.yml
Labels: backport release-1.x
